#!/usr/bin/env python

import os
import subprocess
import time


def call_robot_start():
    try:
        return subprocess.call(["robot", "start", "-u", "pgrice", "--force"])
    except KeyboardInterrupt:
        return 0


def start():
    os.environ['ROS_DISTRO'] = 'indigo'
    os.environ['ROS_ENV_LOADER'] = '/etc/ros/env.sh'
    os.environ['KINECT2'] = 'true'
    os.environ['LD_LIBRARY_PATH'] = '/opt/ros/indigo/lib'
    subprocess.call(['bash', '-c', 'source /opt/ros/indigo/setup.bash'])

    result = call_robot_start()
    while result == 3:
        time.sleep(10)
        result = call_robot_start()


if __name__ == '__main__':
    start()
